<?php
class PerguntasAdicionais
{
    private static function teoria($tema, $enunciado, $alternativas, $correta, $explicacao)
    {
        return compact('tema', 'enunciado', 'alternativas', 'correta', 'explicacao') + ['tipo' => 'Teoria'];
    }

    private static function codigo($tema, $enunciado, $codigo, $alternativas, $correta, $explicacao)
    {
        return compact('tema', 'enunciado', 'codigo', 'alternativas', 'correta', 'explicacao') + ['tipo' => 'Código'];
    }

    public static function listar()
    {
        return [
            'tad-6' => self::teoria('tad',
                'Dois módulos usam a mesma interface de fila. Um armazena os itens em vetor circular; o outro, em nós. Qual parte do TAD deve permanecer igual?',
                ['O formato dos ponteiros.', 'O contrato das operações observáveis.', 'O tamanho de cada nó.', 'A posição física dos itens.'], 1,
                'A implementação interna pode variar. A interface e as regras observáveis do TAD são o compromisso entre os módulos.'),
            'tad-7' => self::teoria('tad',
                'Uma operação de Conta rejeita depósitos negativos. Que propriedade do TAD essa validação protege?',
                ['O invariante do saldo.', 'O nome da classe.', 'O número de parâmetros.', 'A ordem de criação dos objetos.'], 0,
                'Um invariante é uma condição que deve continuar verdadeira depois das operações; impedir entradas inválidas protege o estado.'),
            'tad-8' => self::teoria('tad',
                'Qual situação descreve melhor uma pré-condição de uma operação Remover de pilha?',
                ['A pilha ter sido implementada com vetor.', 'A pilha não estar vazia.', 'O retorno estar formatado como texto.', 'O topo apontar sempre para o último nó removido.'], 1,
                'Remover exige que exista um elemento disponível; a implementação concreta não faz parte da pré-condição abstrata.'),
            'tad-9' => self::codigo('tad',
                'Uma classe encapsula a quantidade. Qual valor será exibido?',
                "private int quantidade = 0;\npublic void Adicionar(int n) { if (n > 0) quantidade += n; }\npublic int Consultar() => quantidade;\n// No mesmo objeto:\nAdicionar(3); Adicionar(-5); Console.WriteLine(Consultar());",
                ['-2', '0', '3', '8'], 2,
                'Adicionar ignora valores não positivos. Somente 3 altera o estado interno.'),
            'tad-10' => self::codigo('tad',
                'O método Retirar retorna false se a operação violar a regra. Qual é a saída?',
                "int saldo = 8;\nbool Retirar(int n) { if (n > saldo) return false; saldo -= n; return true; }\nConsole.WriteLine(Retirar(10));\nConsole.WriteLine(saldo);",
                ['True e -2', 'False e 8', 'False e -2', 'True e 8'], 1,
                'Como 10 excede 8, o método sai antes de mudar saldo.'),
            'tad-11' => self::codigo('tad',
                'Considere a cópia de uma struct em C#. Que valores aparecem?',
                "struct Ponto { public int X; }\nPonto a = new Ponto { X = 2 };\nPonto b = a;\nb.X = 9;\nConsole.WriteLine($\"{a.X} {b.X}\");",
                ['9 9', '2 9', '2 2', '9 2'], 1,
                'Struct é tipo de valor. Atribuir a a b cria uma cópia; mudar b não altera a.'),
            'tad-12' => self::codigo('tad',
                'Qual alternativa completa a operação para impedir que o estado fique negativo?',
                "private int itens = 2;\npublic bool Consumir(int n)\n{\n    // condição faltante\n    itens -= n;\n    return true;\n}",
                ['if (n <= 0 || n > itens) return false;', 'if (n >= 0) itens = 0;', 'if (n > itens) itens -= n;', 'if (itens > 0) return false;'], 0,
                'A validação deve rejeitar quantidades não positivas e quantidades maiores que as disponíveis.'),

            'lisimples-6' => self::teoria('lisimples',
                'Ao inserir no início de uma lista simples, qual ligação deve ser feita antes de trocar Inicio?',
                ['novo.Proximo = Inicio.', 'Fim.Proximo = null.', 'Inicio = Inicio.Proximo.', 'novo.Proximo = novo.'], 0,
                'O novo nó deve apontar para o antigo início antes de se tornar a nova primeira referência.'),
            'lisimples-7' => self::teoria('lisimples',
                'Uma lista simples conhece apenas Inicio e Fim. Por que remover o último nó tende a custar O(n)?',
                ['Porque Fim nunca aponta para um nó.', 'Porque é preciso localizar o penúltimo nó para atualizar Fim.', 'Porque os valores devem ser ordenados antes.', 'Porque a memória precisa ser copiada inteira.'], 1,
                'Sem referência Anterior, o penúltimo nó só é encontrado percorrendo a lista.'),
            'lisimples-8' => self::teoria('lisimples',
                'Ao percorrer uma lista simples, o programa nunca encontra null. Qual erro estrutural pode explicar isso?',
                ['Um nó aponta para outro nó já visitado, formando ciclo.', 'Inicio aponta para o primeiro nó.', 'Fim aponta para null.', 'O valor do primeiro nó é zero.'], 0,
                'Um ciclo impede o percurso de chegar ao fim, podendo causar laço infinito.'),
            'lisimples-9' => self::codigo('lisimples',
                'Inicio aponta para 4 → 7 → null. Que sequência resulta deste trecho?',
                "No n = new No(2);\nn.Proximo = Inicio;\nInicio = n;",
                ['4 → 7 → 2', '2 → 4 → 7', '2 → 7', '4 → 2 → 7'], 1,
                'O novo nó aponta para o antigo início e depois passa a ser o início.'),
            'lisimples-10' => self::codigo('lisimples',
                'Inicio aponta para 3 → 5 → 8 → null. O que o código imprime?',
                "int soma = 0;\nfor (No p = Inicio; p != null; p = p.Proximo) soma += p.Valor;\nConsole.WriteLine(soma);",
                ['8', '11', '16', '3'], 2,
                'O percurso soma os três valores: 3 + 5 + 8 = 16.'),
            'lisimples-11' => self::codigo('lisimples',
                'A lista 1 → 2 → 3 → null tem Inicio em 1. Após o comando, qual nó deixa de ser alcançável a partir de Inicio?',
                'Inicio.Proximo = Inicio.Proximo.Proximo;',
                ['1', '2', '3', 'Nenhum'], 1,
                'O primeiro nó passa a apontar diretamente para 3, ignorando o nó 2.'),
            'lisimples-12' => self::codigo('lisimples',
                'Qual condição deve identificar uma lista simples vazia antes da primeira inserção?',
                "No novo = new No(6);\nif (/* condição */) { Inicio = novo; Fim = novo; }\nelse { Fim.Proximo = novo; Fim = novo; }",
                ['Inicio == null', 'Inicio.Proximo == null', 'Fim.Valor == 0', 'novo.Proximo != null'], 0,
                'Se Inicio é null, não há nó; o novo elemento deve se tornar simultaneamente início e fim.'),

            'lisdupla-6' => self::teoria('lisdupla',
                'Uma lista dupla mantém Fim. Qual operação pode ocorrer em O(1) sem buscar nós por valor?',
                ['Inserir após Fim.', 'Buscar um valor desconhecido.', 'Acessar a posição 100.', 'Contar todos os nós.'], 0,
                'A referência Fim permite ligar um novo nó diretamente à extremidade final.'),
            'lisdupla-7' => self::teoria('lisdupla',
                'Uma lista dupla tem apenas um nó. Após removê-lo, como devem ficar Inicio e Fim?',
                ['Ambos apontam para o nó antigo.', 'Inicio é null e Fim aponta para o nó antigo.', 'Ambos são null.', 'Fim é null e Inicio aponta para o nó antigo.'], 2,
                'Sem elementos, nenhuma das duas extremidades pode continuar apontando para o nó removido.'),
            'lisdupla-8' => self::teoria('lisdupla',
                'Ao inserir X entre A e B em uma lista dupla, quais ligações de B e X precisam existir?',
                ['B.Anterior = X e X.Proximo = B.', 'B.Proximo = X e X.Anterior = B.', 'B.Anterior = A e X.Proximo = A.', 'A.Anterior = B e X.Anterior = null.'], 0,
                'X precisa apontar para B e B precisa reconhecer X como anterior, além das ligações entre A e X.'),
            'lisdupla-9' => self::codigo('lisdupla',
                'Fim aponta para 9 em 3 ↔ 6 ↔ 9. Qual saída resulta do percurso?',
                "for (No p = Fim; p != null; p = p.Anterior) Console.Write(p.Valor + \" \" );",
                ['3 6 9', '9 6 3', '9 3', '6 3'], 1,
                'Partindo de Fim e seguindo Anterior, a ordem é 9, 6, 3.'),
            'lisdupla-10' => self::codigo('lisdupla',
                'A lista não está vazia. Qual instrução deve vir antes de Fim = novo?',
                "No novo = new No(12);\nnovo.Anterior = Fim;\nnovo.Proximo = null;\n// instrução faltante\nFim = novo;",
                ['Inicio = novo;', 'Fim.Proximo = novo;', 'novo.Anterior = null;', 'Fim = null;'], 1,
                'O antigo Fim deve apontar para o novo nó por Proximo antes de a extremidade avançar.'),
            'lisdupla-11' => self::codigo('lisdupla',
                'A lista é A ↔ B ↔ C, e atual aponta para B. O que falta após atual.Anterior.Proximo = atual.Proximo?',
                'atual.Anterior.Proximo = atual.Proximo; // remover B',
                ['atual.Proximo.Anterior = atual.Anterior;', 'atual.Anterior = atual.Proximo;', 'Inicio = atual.Proximo.Proximo;', 'atual.Proximo = atual;'], 0,
                'C.Anterior deve passar a apontar para A para manter o percurso reverso consistente.'),
            'lisdupla-12' => self::codigo('lisdupla',
                'O percurso começa em Inicio de 2 ↔ 4 ↔ 6. Qual valor será exibido?',
                "No p = Inicio.Proximo;\nConsole.WriteLine(p.Anterior.Valor + p.Proximo.Valor);",
                ['4', '6', '8', '12'], 2,
                'p aponta para 4; seu anterior vale 2 e seu próximo vale 6. A soma é 8.'),

            'fila-6' => self::teoria('fila',
                'Uma operação Espiar consulta o início da fila sem desenfileirar. Qual deve ser o estado após a consulta?',
                ['O início avança um nó.', 'A fila permanece igual.', 'O fim passa a ser null.', 'Os itens são invertidos.'], 1,
                'Consultar o primeiro elemento não modifica as referências da fila.'),
            'fila-7' => self::teoria('fila',
                'Uma fila encadeada ficou vazia após a remoção. Qual referência precisa ser limpa além de Inicio?',
                ['Fim.', 'O valor de todos os nós antigos.', 'A prioridade do próximo item.', 'O ponteiro de uma lista dupla.'], 0,
                'Fim também precisa ser null para não apontar para um nó que já saiu.'),
            'fila-8' => self::teoria('fila',
                'Uma fila recebe A, B, C. Ao consultar o início sem remover e depois desenfileirar, qual elemento sai?',
                ['A', 'B', 'C', 'Nenhum'], 0,
                'A consulta não altera a ordem; o elemento mais antigo ainda é A.'),
            'fila-9' => self::codigo('fila',
                'A fila estava vazia. Que sequência fica após as operações?',
                "Enfileirar(4); Enfileirar(7);\nDesenfileirar(); Enfileirar(9);",
                ['4 → 7 → 9', '7 → 9', '9 → 7', '4 → 9'], 1,
                'A remoção retira 4, restando 7; depois 9 entra no fim.'),
            'fila-10' => self::codigo('fila',
                'Na inserção de uma fila vazia, qual atualização evita que Fim fique desatualizado?',
                "No novo = new No(5);\nif (Inicio == null) Inicio = novo;\n// atualização comum a toda inserção",
                ['Fim = novo;', 'Inicio = null;', 'Fim.Proximo = Inicio;', 'novo.Proximo = Inicio;'], 0,
                'O novo nó é o último mesmo quando também é o primeiro.'),
            'fila-11' => self::codigo('fila',
                'A fila contém apenas um nó. Qual condição atualiza Fim depois de remover o início?',
                "Inicio = Inicio.Proximo;\nif (/* condição */) Fim = null;",
                ['Inicio == null', 'Fim.Proximo != null', 'Inicio.Valor == 0', 'Fim == Inicio'], 0,
                'Depois de remover o único nó, Inicio se torna null; Fim também deve ser limpo.'),
            'fila-12' => self::codigo('fila',
                'A fila contém 2 → 5 → 8, com Inicio em 2. Qual valor será mostrado?',
                "Console.WriteLine(Inicio.Proximo.Valor);",
                ['2', '5', '8', 'O código sempre lança exceção.'], 1,
                'Inicio.Proximo aponta para o segundo nó, cujo valor é 5.'),

            'filaprioridade-6' => self::teoria('filaprioridade',
                'A, B e C possuem a mesma prioridade e chegaram nessa ordem. Qual desempate preserva FIFO?',
                ['C, B, A', 'B, A, C', 'A, B, C', 'Ordem aleatória'], 2,
                'Elementos empatados devem sair na mesma ordem em que chegaram.'),
            'filaprioridade-7' => self::teoria('filaprioridade',
                'Em uma fila encadeada ordenada por prioridade decrescente, qual nó é removido primeiro?',
                ['O nó no fim.', 'O nó com o menor valor de prioridade.', 'O nó no início.', 'O nó inserido mais recentemente, sempre.'], 2,
                'A ordenação deixa a maior prioridade no início para remoção direta.'),
            'filaprioridade-8' => self::teoria('filaprioridade',
                'Se a prioridade de um nó no meio mudar, por que pode ser necessário reposicioná-lo?',
                ['Para manter a fila ordenada pela prioridade.', 'Para transformar a fila em pilha.', 'Porque todos os nós precisam trocar de valor.', 'Porque a referência Inicio nunca pode mudar.'], 0,
                'Uma alteração de prioridade pode invalidar a posição atual do nó na ordem de atendimento.'),
            'filaprioridade-9' => self::codigo('filaprioridade',
                'Números maiores têm maior prioridade. Qual elemento será removido primeiro?',
                "Inserir(\"A\", 2); Inserir(\"B\", 6); Inserir(\"C\", 4);\nConsole.WriteLine(Remover());",
                ['A', 'B', 'C', 'Depende do valor textual.'], 1,
                'B tem prioridade 6, maior do que 4 e 2.'),
            'filaprioridade-10' => self::codigo('filaprioridade',
                'A fila está ordenada por prioridade decrescente. Qual condição insere o novo nó antes do início?',
                "if (Inicio == null || /* condição */)\n{ novo.Proximo = Inicio; Inicio = novo; }",
                ['novaPrioridade > Inicio.Prioridade', 'novaPrioridade < Inicio.Prioridade', 'novaPrioridade == 0', 'Inicio.Proximo == null'], 0,
                'A prioridade nova deve superar a maior atual para entrar antes do primeiro nó; empates ficam atrás.'),
            'filaprioridade-11' => self::codigo('filaprioridade',
                'Depois de inserir A(3), B(3) e C(5), qual é a ordem da fila?',
                "Inserir(\"A\", 3); Inserir(\"B\", 3); Inserir(\"C\", 5);",
                ['A, B, C', 'C, A, B', 'C, B, A', 'B, A, C'], 1,
                'C vai à frente por ter prioridade 5. A chegou antes de B no empate de prioridade 3.'),
            'filaprioridade-12' => self::codigo('filaprioridade',
                'Com números maiores indicando maior prioridade, qual comparação faz o percurso passar por nós empatados?',
                "while (atual.Proximo != null && atual.Proximo.Prioridade /* operador */ novaPrioridade)\n    atual = atual.Proximo;",
                ['>', '<', '>=', '=='], 2,
                'Usar >= percorre prioridades maiores e também iguais, preservando a ordem de chegada no empate.'),

            'pilha-1' => self::teoria('pilha',
                'Uma pilha vazia recebe A, B e C. Qual elemento sai no primeiro POP?',
                ['A', 'B', 'C', 'Nenhum'], 2,
                'Pilha segue LIFO: o último a entrar, C, é o primeiro a sair.'),
            'pilha-2' => self::teoria('pilha',
                'Em uma pilha encadeada, onde normalmente ocorrem PUSH e POP para terem custo O(1)?',
                ['No fim, após percorrer tudo.', 'No topo.', 'No nó do meio.', 'No menor valor.'], 1,
                'As duas operações alteram a referência Topo e, por isso, não precisam percorrer a pilha.'),
            'pilha-3' => self::teoria('pilha',
                'Após remover o único nó de uma pilha encadeada, qual deve ser o valor de Topo?',
                ['O nó removido.', 'Um nó com valor zero.', 'null.', 'O próximo nó criado.'], 2,
                'Sem elementos, Topo não deve apontar para nenhum nó.'),
            'pilha-4' => self::teoria('pilha',
                'Qual aplicação usa naturalmente a regra LIFO?',
                ['Atender senhas por ordem de chegada.', 'Desfazer ações recentes em um editor.', 'Manter pessoas por prioridade.', 'Percorrer uma fila pelo início.'], 1,
                'Para desfazer, a última ação realizada precisa ser a primeira a ser revertida.'),
            'pilha-5' => self::teoria('pilha',
                'O que acontece com os demais nós após um POP correto em uma pilha encadeada?',
                ['Todos são removidos.', 'Topo passa a apontar para o antigo próximo nó.', 'A pilha vira uma fila.', 'O último nó passa a ser o topo sem percurso.'], 1,
                'POP retira apenas o nó atual do topo e move Topo para seu Proximo.'),
            'pilha-6' => self::teoria('pilha',
                'Qual é a diferença entre consultar o topo e desempilhar?',
                ['Consultar não altera a pilha; desempilhar remove o topo.', 'Ambos removem todos os nós.', 'Consultar ordena os nós.', 'Desempilhar adiciona um nó no fim.'], 0,
                'Uma consulta apenas lê o valor; POP modifica Topo e devolve ou descarta o elemento retirado.'),
            'pilha-7' => self::codigo('pilha',
                'Qual saída aparece depois das operações LIFO?',
                "Empilhar(4); Empilhar(7); Empilhar(2);\nConsole.WriteLine(Desempilhar());",
                ['4', '7', '2', '13'], 2,
                'O valor 2 foi empilhado por último e está no topo.'),
            'pilha-8' => self::codigo('pilha',
                'Topo aponta para 9 → 5 → null. Qual sequência fica após o PUSH de 3?',
                "No novo = new No(3);\nnovo.Proximo = Topo;\nTopo = novo;",
                ['9 → 5 → 3', '3 → 9 → 5', '3 → 5', '9 → 3 → 5'], 1,
                'O novo nó aponta para o antigo topo e depois se torna o topo.'),
            'pilha-9' => self::codigo('pilha',
                'Topo aponta para 6 → 4 → 1 → null. Após o POP, qual valor fica no topo?',
                "int removido = Topo.Valor;\nTopo = Topo.Proximo;",
                ['6', '4', '1', 'null'], 1,
                'O nó 6 sai; Topo avança para o nó 4.'),
            'pilha-10' => self::codigo('pilha',
                'Qual condição deve impedir um POP inválido?',
                "if (/* condição */) throw new InvalidOperationException();\nint valor = Topo.Valor;\nTopo = Topo.Proximo;",
                ['Topo == null', 'Topo.Proximo != null', 'Topo.Valor > 0', 'Topo != null'], 0,
                'A pilha vazia possui Topo null; acessar Valor nesse estado seria inválido.'),
            'pilha-11' => self::codigo('pilha',
                'Que valor será impresso após dois POPs?',
                "Empilhar(1); Empilhar(2); Empilhar(3);\nDesempilhar(); Desempilhar();\nConsole.WriteLine(Topo.Valor);",
                ['1', '2', '3', 'null'], 0,
                'Os dois POPs retiram 3 e 2. O valor 1 permanece no topo.'),
            'pilha-12' => self::codigo('pilha',
                'Qual valor o percurso acumula em uma pilha 5 → 3 → 2 → null?',
                "int soma = 0;\nfor (No p = Topo; p != null; p = p.Proximo) soma += p.Valor;\nConsole.WriteLine(soma);",
                ['5', '8', '10', '2'], 2,
                'O percurso visita todos os nós e soma 5 + 3 + 2 = 10.')
        ];
    }
}
